Move file check from 'detect' to 'compile'
Because from 'detect' we cannot print any messages for the user.

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -33,8 +33,13 @@ cd "$BUILD_DIR"
 # the file to source, if not, take on ./buildpack-run.sh as the file to source.
 if [[ -f "$ENV_DIR/BUILDPACK_RUN" ]]; then
   buildpack_run=$(cat "$ENV_DIR/BUILDPACK_RUN")
-else
+else if [ -f ./buildpack-run.sh ]]; then
   buildpack_run=./buildpack-run.sh
+else
+  echo "Can't apply heroku-buildpack-run: you have to either set the"
+  echo "config var BUILDPACK_RUN, or add the file buildpack-run.sh"
+  echo "in the root directory of your app."
+  exit 1
 fi
 
 echo "Sourcing $buildpack_run" | sed 's/^/-----> /'
diff --git a/bin/detect b/bin/detect
--- a/bin/detect
+++ b/bin/detect
@@ -22,11 +22,11 @@ BUILD_DIR=$1
 CACHE_DIR=$2
 ENV_DIR=$3
 
-if [[ -f "$BUILD_DIR/buildpack-run.sh" || -f "$ENV_DIR/BUILDPACK_RUN" ]]; then
+#if [[ -f "$BUILD_DIR/buildpack-run.sh" || -f "$ENV_DIR/BUILDPACK_RUN" ]]; then
   echo "Run"
-else
-  echo "Can't apply heroku-buildpack-run: you have to either set the"
-  echo "config var BUILDPACK_RUN, or add the file buildpack-run.sh"
-  echo "in the root directory of your app."
-  exit 1
-fi
+#else
+#  echo "Can't apply heroku-buildpack-run: you have to either set the"
+#  echo "config var BUILDPACK_RUN, or add the file buildpack-run.sh"
+#  echo "in the root directory of your app."
+#  exit 1
+#fi
